import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

export const magicians = [
  'Michael Ammar',
  'Andino',
  'Criss Angel',
  // #region
  'John Henry Anderson',
  'Rolf Andra',
  'Theodore Annemann',
  'Alexander Adrion',
  'Max Auzinger',
  'Ken Bardowicks',
  'Jean Beckerelli',
  'Thimon von Berlepsch',
  'Ali Bongo',
  'Bartolomeo Bosco',
  'Bellachini',
  'Harry Blackstone',
  'David Blaine',
  'Borodin',
  'Derren Brown',
  'Lance Burton',
  'John Calvert',
  'Charles Joseph Carter',
  'Ralfo Chefalo',
  'Magic Christian',
  'Milbourne Christopher',
  'David Copperfield',
  'Mr. Cox',
  'Günther Dammann',
  'Paul Daniels',
  'Dante',
  'William Davenport',
  'Dedi',
  'David Devant',
  'Ludwig Döbler',
  'Thomas Nelson Downs',
  'Joseph Dunninger',
  'Oliver Erens',
  'Ehrlich Brothers',
  'Ottokar Fischer',
  'Flip',
  'Julius Frack',
  'Steven Frayne',
  'Joseph Fröhlich',
  'Wiljalba Frikell',
  'Uri Geller',
  'Horace Goldin',
  'Albert Goshman',
  'Valentino Graziadei',
  'Erik Jan Hanussen',
  'Robert Harbin',
  'Pit Hartling',
  'Richard Hatch',
  'Alexander Heimbürger',
  'Doug Henning',
  'Alexander Herrmann',
  'Compars Herrmann',
  'Johann Nepomuk Hofzinser',
  'Conradi-Horster',
  'Harry Houdini',
  'Kevin James (Zauberer)',
  'Ricky Jay',
  'Joshua Jay',
  'Fred Kaps',
  'Kalanag',
  'Alois Kassner',
  'Jorgos Katsaros',
  'Remo Kell',
  'Harry Kellar',
  'Peter Kersten',
  'Peter Heinz Kersten',
  'Igor Kio',
  'Hans Klok',
  'Buatier de Kolta',
  'Anton Kratky-Baschik',
  'Christopher Köhler',
  'Chung Ling Soo',
  'Fritz Lisetti',
  'Shin Lim',
  'Max Malini',
  'Fu Manchu',
  'Ed Marlo',
  'Robert Marteau',
  'Fredo Marvelli',
  'Marvelli jr.',
  'John Nevil Maskelyne',
  'Luís de Matos',
  'Max Maven',
  'Alexander Merk',
  'Moretti',
  'John Mulholland',
  'Albin Neumann',
  'Natias Neutert',
  'Okito',
  'Penn &amp; Teller',
  'Jürgen Peter (Zauberkünstler)',
  'Peter Helten, der Zauberer mit der Tasche',
  'Philadelphia',
  'Simon Pierro',
  'Joseph Pinetti',
  'Punx',
  'James Randi',
  'Matthias Rauch',
  'Vincent Raven',
  'Fredo Raxon',
  'Tony Rei',
  'Gerd Reitmaier',
  'Claus Reitmaier',
  'Eberhard Riese',
  'Jean Eugène Robert-Houdin',
  'August Roterberg',
  'David Roth (Zauberkünstler)',
  'Jan Rouven',
  'Roxanne',
  'Mario Richter',
  'Rovi - Ivor Parry',
  'Hieronymus Scottus',
  'John Scarne',
  'Siegfried und Roy',
  'Tony Slydini',
  'Cody Stone',
  'Zati Sungur',
  'Alexander Straub',
  'Amélie van Tass',
  'Juan Tamariz',
  'Thommy Ten',
  'Tom Thomson',
  'Ernest Thorn',
  'Helge Thun',
  'Howard Thurston',
  'Tombeck',
  'Topas',
  'Trixini',
  'Peter Valance',
  'Val Valentino',
  'Dai Vernon',
  'Kurt Volkmann',
  'Wittus Witt',
  'Aloys Christof Wilsmann',
  'Florian Zimmer',
  'Jochen Zmeck',
  'Society of American Magicians Hall of Fame'
  //#endregion
];

@Injectable({
  providedIn: 'root',
})
export class MagicansService {
  private itemsPerPage = 10;

  getData(page: number): Observable<{ data: string[], page: number }> {
    const startIndex = (page - 1) * this.itemsPerPage;
    const endIndex = startIndex + this.itemsPerPage;
    const data = magicians.slice(startIndex, endIndex);

    return of({ data, page });
  }
}
